{% set version = '1.0.14' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjlabelled
  version: {{ version|replace("-", "_") }}

source:
  fn: sjlabelled_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sjlabelled_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjlabelled/sjlabelled_{{ version }}.tar.gz
  sha256: 5cbd0d9bb4ae647b928def2b31ca905c5e3593dd0ffc82b3524ef2952afcce2b

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-broom >=0.4.5
    - r-dplyr
    - r-haven >=1.1.2
    - r-magrittr
    - r-prediction
    - r-purrr
    - r-rlang
    - r-snakecase
  run:
    - r-base
    - r-broom >=0.4.5
    - r-dplyr
    - r-haven >=1.1.2
    - r-magrittr
    - r-prediction
    - r-purrr
    - r-rlang
    - r-snakecase

test:
  commands:
    - $R -e "library('sjlabelled')"           # [not win]
    - "\"%R%\" -e \"library('sjlabelled')\""  # [win]

about:
  home: https://github.com/strengejacke/sjlabelled, https://strengejacke.github.io/sjlabelled
  license: GPL-3
  summary: Collection of functions dealing with labelled data, like reading and  writing data
    between R and other statistical software packages like 'SPSS', 'SAS' or 'Stata',
    and working with labelled data. This includes easy ways  to get, set or change value
    and variable label attributes, to convert  labelled vectors into factors or numeric
    (and vice versa), or to deal with  multiple declared missing values.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - ccwang002
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
