{% set version = "1.1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjlabelled
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sjlabelled_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjlabelled/sjlabelled_{{ version }}.tar.gz
  sha256: 9c615d908ff1961ee79e110b20ff52d0588a54cb2ade0abf247fdb5e8f01ddee

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-haven >=1.1.2
    - r-insight >=0.4.1
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tidyselect
  run:
    - r-base
    - r-haven >=1.1.2
    - r-insight >=0.4.1
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tidyselect

test:
  commands:
    - $R -e "library('sjlabelled')"           # [not win]
    - "\"%R%\" -e \"library('sjlabelled')\""  # [win]

about:
  home: https://strengejacke.github.io/sjlabelled
  license: GPL-3
  summary: Collection of functions dealing with labelled data, like reading and  writing data
    between R and other statistical software packages like 'SPSS', 'SAS' or 'Stata',
    and working with labelled data. This includes easy ways  to get, set or change value
    and variable label attributes, to convert  labelled vectors into factors or numeric
    (and vice versa), or to deal with  multiple declared missing values.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: sjlabelled
# Type: Package
# Encoding: UTF-8
# Title: Labelled Data Utility Functions
# Version: 1.1.1
# Date: 2019-09-13
# Authors@R: c( person("Daniel", "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206")), person("David", "Ranzolin", role = "ctb", email = "daranzolin@gmail.com") )
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Collection of functions dealing with labelled data, like reading and  writing data between R and other statistical software packages like 'SPSS', 'SAS' or 'Stata', and working with labelled data. This includes easy ways  to get, set or change value and variable label attributes, to convert  labelled vectors into factors or numeric (and vice versa), or to deal with  multiple declared missing values.
# License: GPL-3
# Depends: R (>= 3.2)
# Imports: haven (>= 1.1.2), insight (>= 0.4.1), magrittr, purrr, rlang, stats, tidyselect, tools, utils
# Suggests: dplyr, sjmisc, sjPlot, knitr, rmarkdown, snakecase, testthat
# URL: https://strengejacke.github.io/sjlabelled
# BugReports: https://github.com/strengejacke/sjlabelled/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-09-13 11:55:58 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>), David Ranzolin [ctb]
# Repository: CRAN
# Date/Publication: 2019-09-13 13:00:02 UTC
