appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GZICVLDjx5QmP7QNm8hLU8p5yJLrJ68g2LlGW+PewRu5Vcp/qgVNp1ABx3AYDRZX67a4mDprlr5Chx8OaOhSRPUlJyEtQXc9lL6X3x3EoCKBlD73BORVVAf1xoVeTsGGtpeMJzrw3QhaRBfUz7RveHjSGXupitE5U5Choi2e4ZEWjNZkCnuFwLZt/Bt/tUCs3NhlvGE675xubffcuzvXSKPlq4HkaUF57GG+IzLCPxtxB0aCC2VsS+8QfhWCWHJmF85oQtD1cFpMbsJftYoXaWKtezTaCzXB91BQgdS1qQ6y36RG6VsLLc5h0diQuubq7LyF4ZN2MiALqfHOxLz9CxifTTLfOGvJwPgjC/UpC5CIPu+1pZ65roLaecIE4woYyfgTd/ig41dsmTXlaeidKSi0H1obhZ279Je0dyt7wBe6P084Pufg0KMbRepbmn6BUdlZ+zZ3xjy7HAGXhcEnIm+4C2b0NyLY+nexNH5jOVnZ8VDn+qF5kJoz0Ma6aigIaYLmpE+lWhFA44Yg75PjMCyAO+KlNLpVe5eyGRNTfSEfzX/S8KmgeAhUjmjI2Li1AV3mye5dJdIGwmcxjTXhj1MNVy/kuMciOC3ZoLedp/5PmfVDukL0Fqmk0MTK0GNcnGbfL7JuI5/YapCipM/nXVVZIl8vs8SPdRv85WZ9veg=}
