travis:
  secure:
    BINSTAR_TOKEN: qicTR+Q52bQjAWx0rnqZw0hfCDd83kX7/yWewXEe5Jd0AhEcasxC4Z9yIkgYicrlwbSf3NqAfYRQ8LLIVlED7je+/cHqE56cCdBP8hW2XXSIrLaaN/pkqa7BqWb0ONqYfLwuBrfzhly11I2jVXruyepulP3tQ6gtB9rmmr6iPUT+p+9yMG5Ojc+E4jY/rg9DhAKtzEsL+5zotG0c3Wng+hf7rXOKxhBlWRtH1EkQG1Dq3Xsad+8FZ75RfD+XWdOo7Bmu8fDL2cTiVeD/8Y4D6vEE14pbhCC44Lj3vuiWaWt2efjU7NnWeiEL/gql759rQTsP1NSq8Cm1WkCSv4SpZvvyIVlKcVR5Sfs5S08/JApluGgeXcOQR5zu+fxDgI6xfUmegwQPTzfyDLI9LlwuGcT1DY26H6ht0nVGwwYxCGva0cLUvDnhBsw/F+EoJ8M0EQFrw30J/ebDLpd60/VpdjaWfojVnVlWAmld46wIIloPp4W5N3qrwutd9gAVZx+sB0iDMOfgDMri2ZqvhxKpZ8WQlmFgCLAsdRTZ6vNEkXAhcRJDMJMTdfIzYzbEtk+Q1t1qqaLTqRKt7VSR8r2zrLQFd7W06aeU6DOOLeOYGzGiKoqXlJCfPYKC90GU2a58yawzecMvkLWN+oJss68x+7AWYWRa+LE0zh/mOZ7tgDA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
